# Default values for synapse.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "matrixdotorg/synapse"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.25.0"

synapse:
  server_name: "example.com"
  report_stats: "yes"
  config_dir: "/data" 
  config_path: "/data/homeserver.yaml" 
  data_dir: "/data"  
  uid: 991
  gid: 991
  port: 8008
  storage:
    className: standard
    size: 50Gi

ingress:
  enabled: false
  #metallbAddressPool: "mypool"

kubegres:
  replicaCount: 3
  database:
    name: synapsedb
    user: synapseuser
    port: 5432
    size: 200Mi
    storageClassName: standard
    superUserPassword: secret123 
    replicationUserPassword: secret123
    myDbUserPassword: secret123
