apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: mypostgres
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie

spec:

   replicas: 1
   image: postgres:14.1
   port: 5432

   database:
      size: 900Mi
      storageClassName: openebs-lvmpv
      volumeMount: /var/lib/postgresql/data

   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: mypostgres-secret
              key: superUserPassword

      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: mypostgres-secret
              key: replicationUserPassword
