apiVersion: v1
kind: Secret
metadata:
  name: mypostgres-secret
  namespace: default
type: Opaque
stringData:
  superUserPassword: changeme-postgresSuperUserPsw
  replicationUserPassword: changeme-postgresReplicaPsw
