apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace:  {{ .Release.Namespace }}
type: Opaque
stringData:
{{- if .Values.database.superUserPassword }}
  superUserPassword: {{ .Values.database.superUserPassword }}
{{- else }}
  superUserPassword: {{ randAlphaNum 33 }}
{{- end }}
{{- if .Values.database.replicationUserPassword }}
  replicationUserPassword: {{ .Values.database.replicationUserPassword }}
{{- else }}
  replicationUserPassword: {{ randAlphaNum 33 }}
{{- end }}
{{- if .Values.database.myDbUserPassword }}
  myDbUserPassword: {{ .Values.database.myDbUserPassword }}
{{- else }}
  myDbUserPassword: {{ randAlphaNum 33 }}
{{- end }}
