apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-synapse
  namespace:  {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: synapse
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: synapse
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: {{ .Release.Name }}-synapse
        args: ["generate"]
        env:
        - name: SYNAPSE_SERVER_NAME
          value: {{ .Values.synapse.server_name |quote }} 
        - name: SYNAPSE_REPORT_STATS
          value: {{ .Values.synapse.report_stats | quote }} 
        volumeMounts:
        - name: data
          mountPath: /data
        ports:
          - containerPort: {{ .Values.synapse.port }} 
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pv-claim
