apiVersion: v1
kind: PersistentVolume
metadata:
   name: postgres-pv
   labels:
     pvc_type: postgres-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
   - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
   path: /PATH/TO/WHERE/DATA/SHOULD/BE/STORED
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 30Gi
  selector:
    matchLabels:
      pvc_type:  postgres-pv
