apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pv-claim
  namespace:  {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.synapse.storage.className }} 
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.synapse.storage.size }} 
